##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32F756ZG-Nucleo144 =============================
	+@make --no-print-directory -f ./make/stm32f756zg_nucleo144.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f ./make/stm32f756zg_nucleo144.make clean
	@echo

#
##############################################################################
