
/**
 ******************************************************************************
 * @file       images.h
 * @author     dRonin, http://dRonin.org/, Copyright (C) 2016
 * @author     The OpenPilot Team, http://www.openpilot.org, Copyright (C) 2012
 * @author     Thomas Oldbury Copyright (C) 2010
 * @addtogroup dRonin Modules
 * @{
 * @addtogroup OnScreenDisplay Module
 * @{
 * @brief Fonts for OSD
 *****************************************************************************/
/*
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
 * Additional note on redistribution: The copyright and license notices above
 * must be maintained in each individual source file that is a derivative work
 * of this source file; otherwise redistribution is prohibited.
 *
 * NOTE: This file is generated by encode_fonts.py DO NOT EDIT!
 * NOTE: Some fonts are CC 3.0 BY-SA and note GPL licensed. See FONT_LICENSE.txt
 */



#ifndef IMAGES_H
#define IMAGES_H

#include <stdint.h>


#if defined(PIOS_VIDEO_SPLITBUFFER)
struct Image {
	uint16_t width;
	uint16_t height;
	uint8_t* mask;
	uint8_t* level;
};
#else
struct Image {
	uint16_t width;
	uint16_t height;
	uint8_t* data;
};
#endif


#define NUM_IMAGES  2

#define MAINLOGO 0
#define USERLOGO 1


extern const struct Image image_mainlogo;
extern const struct Image image_userlogo;


#endif /* IMAGES_H */
