##############################################################################
# Multi-project makefile rules
#

all:
	@echo
	@echo === Building for STM32F746-Discovery ===============================
	+@make --no-print-directory -f make/stm32f746_discovery.make all
	@echo ====================================================================
	@echo

clean:
	@echo
	+@make --no-print-directory -f make/stm32f746_discovery.make clean
	@echo

#
##############################################################################
