#!/bin/bash
# Auto-generate WASM PG registry from source code
# This script extracts all PG_REGISTER* calls and creates a manual registry

set -euo pipefail

INAV_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUTPUT_FILE="$INAV_ROOT/src/main/target/SITL/wasm_pg_registry.c"

echo "Generating WASM PG registry from source code..."

# Extract all PG names from PG_REGISTER calls
# Pattern: PG_REGISTER(type, NAME, pgn, version) - NAME is 2nd param
# Pattern: PG_REGISTER_ARRAY(type, size, NAME, pgn, version) - NAME is 3rd param
#
# Exclude files that are not compiled for SITL:
# - io/ledstrip.c (LED strips not supported on SITL)
# - drivers/light_ws2811strip.c (WS2811 LEDs not on SITL)
# - sensors/esc_sensor.c (ESC sensor protocol not on SITL)
# - io/piniobox.c (Pin I/O box not on SITL)
# - io/osd_joystick.c (OSD joystick not on SITL)
# - io/lights.c (Lights not on SITL)
# - sensors/rpm_filter.c (RPM filter hardware-specific)
# - telemetry/smartport_master.c (SmartPort master not on SITL)
PG_NAMES=$(cd "$INAV_ROOT" && grep -r "^PG_REGISTER" --include="*.c" src/main/ | \
    grep -v "ledstrip.c:\|light_ws2811strip.c:\|esc_sensor.c:\|piniobox.c:\|osd_joystick.c:\|lights.c:\|rpm_filter.c:\|smartport_master.c:" | \
    sed -E 's/.*:PG_REGISTER_ARRAY[^(]*\([^,]*,[^,]*, ([a-zA-Z0-9_]+),.*/\1/; t; s/.*:PG_REGISTER[^(]*\([^,]*, ([a-zA-Z0-9_]+),.*/\1/' | \
    sort -u)

PG_COUNT=$(echo "$PG_NAMES" | wc -l)

echo "Found $PG_COUNT parameter groups"

# Generate the C file
cat > "$OUTPUT_FILE" << 'EOF_HEADER'
/*
 * WASM PG Registry - Auto-generated by generate_wasm_pg_registry.sh
 *
 * WebAssembly linker (wasm-ld) does not support GNU LD linker script features
 * like PROVIDE_HIDDEN and custom section boundary symbols (__start/__stop).
 *
 * This file manually declares all PG registry symbols and provides the
 * __pg_registry_start and __pg_registry_end pointers for WASM builds.
 *
 * IMPORTANT: The registry is stored as a contiguous array of pgRegistry_t STRUCTS
 * (not pointers!) because PG_FOREACH iterates with reg++ which moves by
 * sizeof(pgRegistry_t). The structs are copied from scattered source registries
 * at runtime by wasmPgRegistryInit().
 */

#ifdef __EMSCRIPTEN__

#include <stdbool.h>
#include "config/parameter_group.h"

EOF_HEADER

# Generate extern declarations
echo "// External declarations for all PG registries" >> "$OUTPUT_FILE"
for name in $PG_NAMES; do
    echo "extern const pgRegistry_t ${name}_Registry;" >> "$OUTPUT_FILE"
done

echo "" >> "$OUTPUT_FILE"
echo "// Number of registry entries" >> "$OUTPUT_FILE"
echo "#define WASM_PG_REGISTRY_COUNT $PG_COUNT" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "// Array of pointers to all PG registry entries (for building contiguous array)" >> "$OUTPUT_FILE"
echo "static const pgRegistry_t* const __wasm_pg_registry_ptrs[WASM_PG_REGISTRY_COUNT] = {" >> "$OUTPUT_FILE"
for name in $PG_NAMES; do
    echo "    &${name}_Registry," >> "$OUTPUT_FILE"
done
echo "};" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
cat >> "$OUTPUT_FILE" << 'EOF_STRUCTS'
// Contiguous array of registry STRUCTS (not pointers!) - initialized at startup
// PG_FOREACH iterates with reg++ which moves by sizeof(pgRegistry_t)
// This MUST be an array of structs, not an array of pointers
static pgRegistry_t __wasm_pg_registry[WASM_PG_REGISTRY_COUNT];

// Flag to track if registry has been initialized
static bool __wasm_pg_registry_initialized = false;

// Define the __pg_registry_start and __pg_registry_end symbols
// These point to the contiguous struct array (after initialization)
const pgRegistry_t* const __pg_registry_start = &__wasm_pg_registry[0];
const pgRegistry_t* const __pg_registry_end = &__wasm_pg_registry[WASM_PG_REGISTRY_COUNT];

// Initialize the contiguous registry array by copying from scattered source registries
// This must be called early in init() before any PG_FOREACH usage
void wasmPgRegistryInit(void)
{
    if (__wasm_pg_registry_initialized) {
        return;
    }

    for (int i = 0; i < WASM_PG_REGISTRY_COUNT; i++) {
        __wasm_pg_registry[i] = *__wasm_pg_registry_ptrs[i];
    }

    __wasm_pg_registry_initialized = true;
}
EOF_STRUCTS

echo "" >> "$OUTPUT_FILE"
echo "// Stub for reset data section (not used in WASM builds)" >> "$OUTPUT_FILE"
echo "static const uint8_t __wasm_pg_resetdata_stub[1] = {0};" >> "$OUTPUT_FILE"
echo "const uint8_t* const __pg_resetdata_start = &__wasm_pg_resetdata_stub[0];" >> "$OUTPUT_FILE"
echo "const uint8_t* const __pg_resetdata_end = &__wasm_pg_resetdata_stub[0];" >> "$OUTPUT_FILE"

echo "" >> "$OUTPUT_FILE"
echo "#endif // __EMSCRIPTEN__" >> "$OUTPUT_FILE"

echo "Generated: $OUTPUT_FILE"
echo "Registry contains $PG_COUNT entries"
