var searchData=
[
  ['c',['c',['../structcmsis__nn__dims.html#ac9c268ab90554ab8ea2c3d76ecf1ed6c',1,'cmsis_nn_dims']]],
  ['ch_5fmult',['ch_mult',['../structcmsis__nn__dw__conv__params.html#aa613968e07c396755c2a6def8ecded79',1,'cmsis_nn_dw_conv_params']]],
  ['clamp',['CLAMP',['../arm__nnsupportfunctions_8h.html#abe05f0e80d965ae31dec16ba4063f48a',1,'arm_nnsupportfunctions.h']]],
  ['clamp_5foutput',['clamp_output',['../arm__max__pool__s16_8c.html#a464e5d2cf70e82eb27be23b94a793cf6',1,'clamp_output(int16_t *source, int32_t length, const int16_t act_min, const int16_t act_max):&#160;arm_max_pool_s16.c'],['../arm__max__pool__s8_8c.html#ae73d902e6c38cf63ab235d6c4a3ff3b0',1,'clamp_output(q7_t *source, int32_t length, const int32_t act_min, const int32_t act_max):&#160;arm_max_pool_s8.c']]],
  ['cmakelists_2etxt',['CMakeLists.txt',['../CMakeLists_8txt.html',1,'']]],
  ['cmakelists_2etxt',['CMakeLists.txt',['../ConcatenationFunctions_2CMakeLists_8txt.html',1,'']]],
  ['cmakelists_2etxt',['CMakeLists.txt',['../ConvolutionFunctions_2CMakeLists_8txt.html',1,'']]],
  ['cmsis_5fnn_5factivation',['cmsis_nn_activation',['../structcmsis__nn__activation.html',1,'']]],
  ['cmsis_5fnn_5fcontext',['cmsis_nn_context',['../structcmsis__nn__context.html',1,'']]],
  ['cmsis_5fnn_5fconv_5fparams',['cmsis_nn_conv_params',['../structcmsis__nn__conv__params.html',1,'']]],
  ['cmsis_5fnn_5fdims',['cmsis_nn_dims',['../structcmsis__nn__dims.html',1,'']]],
  ['cmsis_5fnn_5fdw_5fconv_5fparams',['cmsis_nn_dw_conv_params',['../structcmsis__nn__dw__conv__params.html',1,'']]],
  ['cmsis_5fnn_5ffc_5fparams',['cmsis_nn_fc_params',['../structcmsis__nn__fc__params.html',1,'']]],
  ['cmsis_5fnn_5fper_5fchannel_5fquant_5fparams',['cmsis_nn_per_channel_quant_params',['../structcmsis__nn__per__channel__quant__params.html',1,'']]],
  ['cmsis_5fnn_5fper_5ftensor_5fquant_5fparams',['cmsis_nn_per_tensor_quant_params',['../structcmsis__nn__per__tensor__quant__params.html',1,'']]],
  ['cmsis_5fnn_5fpool_5fparams',['cmsis_nn_pool_params',['../structcmsis__nn__pool__params.html',1,'']]],
  ['cmsis_5fnn_5fsoftmax_5flut_5fs16',['cmsis_nn_softmax_lut_s16',['../structcmsis__nn__softmax__lut__s16.html',1,'']]],
  ['cmsis_5fnn_5fsvdf_5fparams',['cmsis_nn_svdf_params',['../structcmsis__nn__svdf__params.html',1,'']]],
  ['cmsis_5fnn_5ftile',['cmsis_nn_tile',['../structcmsis__nn__tile.html',1,'']]],
  ['compare_5fand_5freplace_5fif_5flarger',['compare_and_replace_if_larger',['../arm__max__pool__s16_8c.html#a61d8f1ffa151d8a3327aea577f8c63a3',1,'arm_max_pool_s16.c']]],
  ['compare_5fand_5freplace_5fif_5flarger_5fq7',['compare_and_replace_if_larger_q7',['../arm__max__pool__s8_8c.html#a3b21bd4a5703839f9ffa5407502c302c',1,'arm_max_pool_s8.c']]],
  ['concatenation_20functions',['Concatenation Functions',['../group__Concatenation.html',1,'']]],
  ['cmsis_20nn_20software_20library',['CMSIS NN Software Library',['../index.html',1,'']]],
  ['convolution_20functions',['Convolution Functions',['../group__NNConv.html',1,'']]]
];
