RELEASE_TARGETS = AIRHEROF3 AIRHEROF3_QUAD \
                  COLIBRI_RACE LUX_RACE FURYF3 FURYF3_SPIFLASH OMNIBUS RCEXPLORERF3 RMDO SPARKY \
                  KFC32F3_INAV FALCORE BETAFLIGHTF3 MOTOLAB \
                  SPRACINGF3 SPRACINGF3EVO SPRACINGF3EVO_1SS SPRACINGF3MINI SPRACINGF3NEO \
                  AIRBOTF4 ANYFC BLUEJAYF4 COLIBRI F4BY OMNIBUSF4 OMNIBUSF4PRO OMNIBUSF4V3 OMNIBUSF4PRO_LEDSTRIPM5 QUANTON REVO SPARKY2 YUPIF4 KROOZX BEEROTORF4 \
                  SPRACINGF4EVO PIKOBLX DYSF4PRO MATEKF405 MATEKF405OSD CLRACINGF4AIR CLRACINGF4AIRV2 PIXRACER \
                  BETAFLIGHTF4 FF_F35_LIGHTNING FF_FORTINIF4 KAKUTEF4 KAKUTEF4V2 \
                  ANYFCF7 ANYFCF7_EXTERNAL_BARO ANYFCM7 ALIENFLIGHTNGF7 OMNIBUSF7 OMNIBUSF7V2 MATEKF722 \
                  ASGARD32F4 FIREWORKSV2 OMNIBUSF7NXT MATEKF405SE