var searchData=
[
  ['canberra_20distance',['Canberra distance',['../group__Canberra.html',1,'']]],
  ['complex_20fft_20tables',['Complex FFT Tables',['../group__CFFT__CIFFT.html',1,'']]],
  ['chebyshev_20distance',['Chebyshev distance',['../group__Chebyshev.html',1,'']]],
  ['class_20marks_20example',['Class Marks Example',['../group__ClassMarks.html',1,'']]],
  ['complex_20conjugate',['Complex Conjugate',['../group__cmplx__conj.html',1,'']]],
  ['complex_20dot_20product',['Complex Dot Product',['../group__cmplx__dot__prod.html',1,'']]],
  ['complex_20magnitude',['Complex Magnitude',['../group__cmplx__mag.html',1,'']]],
  ['complex_20magnitude_20squared',['Complex Magnitude Squared',['../group__cmplx__mag__squared.html',1,'']]],
  ['complex_2dby_2dcomplex_20multiplication',['Complex-by-Complex Multiplication',['../group__CmplxByCmplxMult.html',1,'']]],
  ['complex_2dby_2dreal_20multiplication',['Complex-by-Real Multiplication',['../group__CmplxByRealMult.html',1,'']]],
  ['complex_20matrix_20multiplication',['Complex Matrix Multiplication',['../group__CmplxMatrixMult.html',1,'']]],
  ['complex_20fft_20functions',['Complex FFT Functions',['../group__ComplexFFT.html',1,'']]],
  ['convolution',['Convolution',['../group__Conv.html',1,'']]],
  ['convolution_20example',['Convolution Example',['../group__ConvolutionExample.html',1,'']]],
  ['correlation',['Correlation',['../group__Corr.html',1,'']]],
  ['correlation_20distance',['Correlation distance',['../group__Correlation.html',1,'']]],
  ['cosine',['Cosine',['../group__cos.html',1,'']]],
  ['cosine_20distance',['Cosine distance',['../group__CosineDist.html',1,'']]],
  ['convert_2016_2dbit_20floating_20point_20value',['Convert 16-bit floating point value',['../group__f16__to__x.html',1,'']]],
  ['convert_2032_2dbit_20floating_20point_20value',['Convert 32-bit floating point value',['../group__float__to__x.html',1,'']]],
  ['complex_20math_20functions',['Complex Math Functions',['../group__groupCmplxMath.html',1,'']]],
  ['controller_20functions',['Controller Functions',['../group__groupController.html',1,'']]],
  ['cityblock_20_28manhattan_29_20distance',['Cityblock (Manhattan) distance',['../group__Manhattan.html',1,'']]],
  ['cholesky_20and_20ldlt_20decompositions',['Cholesky and LDLT decompositions',['../group__MatrixChol.html',1,'']]],
  ['complex_20matrix_20transpose',['Complex Matrix Transpose',['../group__MatrixComplexTrans.html',1,'']]],
  ['convert_2016_2dbit_20fixed_20point_20value',['Convert 16-bit fixed point value',['../group__q15__to__x.html',1,'']]],
  ['convert_2032_2dbit_20fixed_20point_20value',['Convert 32-bit fixed point value',['../group__q31__to__x.html',1,'']]],
  ['convert_208_2dbit_20fixed_20point_20value',['Convert 8-bit fixed point value',['../group__q7__to__x.html',1,'']]],
  ['cubic_20spline_20interpolation',['Cubic Spline Interpolation',['../group__SplineInterpolate.html',1,'']]]
];
