
set(DSDLC_GENERATED_DIR "${MAIN_LIB_DIR}/main/Dronecan/dsdlc_generated")

set(DSDLC_GENERATED_SRC
    dronecan.protocol.CanStats.c                                
    dronecan.protocol.FlexDebug.c                               
    dronecan.protocol.GlobalTime.c                              
    dronecan.protocol.Stats.c                                   
    dronecan.remoteid.ArmStatus.c                               
    dronecan.remoteid.BasicID.c                                 
    dronecan.remoteid.Location.c                                
    dronecan.remoteid.OperatorID.c                              
    dronecan.remoteid.SecureCommand_req.c                       
    dronecan.remoteid.SecureCommand_res.c                       
    dronecan.remoteid.SelfID.c                                  
    dronecan.remoteid.System.c                                  
    dronecan.sensors.hygrometer.Hygrometer.c                    
    dronecan.sensors.magnetometer.MagneticFieldStrengthHiRes.c  
    dronecan.sensors.rc.RCInput.c                               
    dronecan.sensors.rpm.RPM.c                                                                                 
    uavcan.CoarseOrientation.c                                  
    uavcan.equipment.actuator.ArrayCommand.c                    
    uavcan.equipment.actuator.Command.c                         
    uavcan.equipment.actuator.Status.c                          
    uavcan.equipment.ahrs.MagneticFieldStrength2.c              
    uavcan.equipment.ahrs.MagneticFieldStrength.c               
    uavcan.equipment.ahrs.RawIMU.c                              
    uavcan.equipment.ahrs.Solution.c                            
    uavcan.equipment.air_data.AngleOfAttack.c                   
    uavcan.equipment.air_data.IndicatedAirspeed.c               
    uavcan.equipment.air_data.RawAirData.c                      
    uavcan.equipment.air_data.Sideslip.c                        
    uavcan.equipment.air_data.StaticPressure.c                  
    uavcan.equipment.air_data.StaticTemperature.c               
    uavcan.equipment.air_data.TrueAirspeed.c                    
    uavcan.equipment.camera_gimbal.AngularCommand.c             
    uavcan.equipment.camera_gimbal.GEOPOICommand.c              
    uavcan.equipment.camera_gimbal.Mode.c                       
    uavcan.equipment.camera_gimbal.Status.c                     
    uavcan.equipment.device.Temperature.c                       
    uavcan.equipment.esc.RawCommand.c                           
    uavcan.equipment.esc.RPMCommand.c                           
    uavcan.equipment.esc.Status.c                               
    uavcan.equipment.esc.StatusExtended.c                       
    uavcan.equipment.gnss.Auxiliary.c                           
    uavcan.equipment.gnss.ECEFPositionVelocity.c                
    uavcan.equipment.gnss.Fix2.c                                
    uavcan.equipment.gnss.Fix.c                                 
    uavcan.equipment.gnss.RTCMStream.c                          
    uavcan.equipment.hardpoint.Command.c                        
    uavcan.equipment.hardpoint.Status.c                         
    uavcan.equipment.ice.FuelTankStatus.c                       
    uavcan.equipment.ice.reciprocating.CylinderStatus.c         
    uavcan.equipment.ice.reciprocating.Status.c                 
    uavcan.equipment.indication.BeepCommand.c                   
    uavcan.equipment.indication.LightsCommand.c                 
    uavcan.equipment.indication.RGB565.c                        
    uavcan.equipment.indication.SingleLightCommand.c            
    uavcan.equipment.power.BatteryInfo.c                        
    uavcan.equipment.power.CircuitStatus.c                      
    uavcan.equipment.power.PrimaryPowerSupplyStatus.c           
    uavcan.equipment.range_sensor.Measurement.c                 
    uavcan.equipment.safety.ArmingStatus.c 
    uavcan.navigation.GlobalNavigationSolution.c
    uavcan.protocol.AccessCommandShell_req.c
    uavcan.protocol.AccessCommandShell_res.c
    uavcan.protocol.CANIfaceStats.c
    uavcan.protocol.DataTypeKind.c
    uavcan.protocol.debug.KeyValue.c
    uavcan.protocol.debug.LogLevel.c
    uavcan.protocol.debug.LogMessage.c
    uavcan.protocol.dynamic_node_id.Allocation.c
    uavcan.protocol.dynamic_node_id.server.AppendEntries_req.c
    uavcan.protocol.dynamic_node_id.server.AppendEntries_res.c
    uavcan.protocol.dynamic_node_id.server.Discovery.c
    uavcan.protocol.dynamic_node_id.server.Entry.c
    uavcan.protocol.dynamic_node_id.server.RequestVote_req.c
    uavcan.protocol.dynamic_node_id.server.RequestVote_res.c
    uavcan.protocol.enumeration.Begin_req.c
    uavcan.protocol.enumeration.Begin_res.c
    uavcan.protocol.enumeration.Indication.c
    uavcan.protocol.file.BeginFirmwareUpdate_req.c
    uavcan.protocol.file.BeginFirmwareUpdate_res.c
    uavcan.protocol.file.Delete_req.c
    uavcan.protocol.file.Delete_res.c
    uavcan.protocol.file.EntryType.c
    uavcan.protocol.file.Error.c
    uavcan.protocol.file.GetDirectoryEntryInfo_req.c
    uavcan.protocol.file.GetDirectoryEntryInfo_res.c
    uavcan.protocol.file.GetInfo_req.c
    uavcan.protocol.file.GetInfo_res.c
    uavcan.protocol.file.Path.c
    uavcan.protocol.file.Read_req.c
    uavcan.protocol.file.Read_res.c
    uavcan.protocol.file.Write_req.c
    uavcan.protocol.file.Write_res.c
    uavcan.protocol.GetDataTypeInfo_req.c
    uavcan.protocol.GetDataTypeInfo_res.c
    uavcan.protocol.GetNodeInfo_req.c
    uavcan.protocol.GetNodeInfo_res.c
    uavcan.protocol.GetTransportStats_req.c
    uavcan.protocol.GetTransportStats_res.c
    uavcan.protocol.GlobalTimeSync.c
    uavcan.protocol.HardwareVersion.c
    uavcan.protocol.NodeStatus.c
    uavcan.protocol.Panic.c
    uavcan.protocol.param.Empty.c
    uavcan.protocol.param.ExecuteOpcode_req.c
    uavcan.protocol.param.ExecuteOpcode_res.c
    uavcan.protocol.param.GetSet_req.c
    uavcan.protocol.param.GetSet_res.c
    uavcan.protocol.param.NumericValue.c
    uavcan.protocol.param.Value.c
    uavcan.protocol.RestartNode_req.c
    uavcan.protocol.RestartNode_res.c
    uavcan.protocol.SoftwareVersion.c
    uavcan.Timestamp.c
    uavcan.tunnel.Broadcast.c
    uavcan.tunnel.Call_req.c
    uavcan.tunnel.Call_res.c
    uavcan.tunnel.Protocol.c
    uavcan.tunnel.SerialConfig.c
    uavcan.tunnel.Targetted.c
)

list(TRANSFORM DSDLC_GENERATED_SRC PREPEND "${DSDLC_GENERATED_DIR}/src/")

set(DSDLC_GENERATED_DIRS
    ${DSDLC_GENERATED_DIR}/include
)


